In [1]:
try:
    %tensorflow_version 2.x
except Exception:
    pass

In [2]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [3]:
# 常數
tf.constant(666)

<tf.Tensor: shape=(), dtype=int32, numpy=666>

In [4]:
tf.constant([2, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [5]:
tf.constant(.123)

<tf.Tensor: shape=(), dtype=float32, numpy=0.123>

In [6]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [8]:
tf.constant("Hello TensorFlow!")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello TensorFlow!'>

In [11]:
import numpy as np
t1 = np.array([1, 2, 3])
tf.convert_to_tensor(t1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
# 變數
# 預設 dtype=int32
tf.zeros([2, 3], tf.float64)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [16]:
# 預設 dtype=float32
tf.ones([2, 3], tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)>

In [19]:
tf.linspace(1.2, 5.6, 5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.2      , 2.3      , 3.3999999, 4.5      , 5.6      ],
      dtype=float32)>

In [20]:
# 預設 start=0, delta=1
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [21]:
tf.range(2.0, 5.0, 0.75)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.  , 2.75, 3.5 , 4.25], dtype=float32)>

In [25]:
t1 = tf.ones(9)
print(t1)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(9,), dtype=float32)


In [29]:
t2 = tf.Variable(t1, name='(*‘ v`*)')
print(t2)

<tf.Variable '(*‘ v`*):0' shape=(9,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>


In [32]:
t2.trainable

True