In [2]:
try:
    %tensorflow_version 2.x
except Exception:
    pass

In [3]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [3]:
# 常數
tf.constant(666)

<tf.Tensor: shape=(), dtype=int32, numpy=666>

In [4]:
tf.constant([2, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [5]:
tf.constant(.123)

<tf.Tensor: shape=(), dtype=float32, numpy=0.123>

In [7]:
tf.constant([[True, False], [True, False], [False, True]])

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True, False],
       [ True, False],
       [False,  True]])>

In [8]:
tf.constant("Hello TensorFlow!")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello TensorFlow!'>

In [9]:
import numpy as np
t1 = np.array([1, 2, 3])
tf.convert_to_tensor(t1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
# 變數
# 預設 dtype=int32
tf.zeros([2, 3], tf.float64)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [10]:
# 預設 dtype=float32
tf.ones([2, 3], tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)>

In [11]:
# 等差排布的序列
tf.linspace(1.2, 5.6, 5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.2      , 2.3      , 3.3999999, 4.5      , 5.6      ],
      dtype=float32)>

In [12]:
# 預設 start=0, delta=1
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [21]:
tf.range(2.0, 5.0, 0.75)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.  , 2.75, 3.5 , 4.25], dtype=float32)>

In [16]:
t2 = tf.ones(9)
t3 = tf.Variable(t2, name='(*‘ v`*)')
print(t3)

<tf.Variable '(*‘ v`*):0' shape=(9,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>


In [17]:
t3.trainable

True

In [4]:
# 佔位符
t1 = tf.zeros([6, 6])
t1

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
tf.zeros_like(t1)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
tf.fill([6, 6], 0.)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
# 平均值，標準差，種子
# 從正態分佈中輸出隨機值
tf.random.normal([2, 3], mean=2, stddev=4, seed=12)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.25347447,  5.37991   ,  1.9527606 ],
       [-1.5376031 ,  1.2588985 ,  2.8478067 ]], dtype=float32)>

In [8]:
# 從截斷的正態分佈中輸出隨機值
# 大於平均值兩個標準差則重新產生
tf.random.truncated_normal([2, 3], mean=2, stddev=2, seed=12)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.1267372 ,  3.689955  ,  1.9763802 ],
       [ 0.23119843, -1.87749   ,  3.1265476 ]], dtype=float32)>

In [9]:
# min, max 之間均勻分布
tf.random.uniform([2, 3], minval=3, maxval=5, seed=12)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4.272305 , 4.8481827, 4.3525543],
       [4.0042505, 4.9222994, 4.771344 ]], dtype=float32)>

In [10]:
# 權重
weights = tf.Variable(tf.random.normal([100, 100], stddev=2))
# 偏置
biases = tf.Variable(tf.zeros([100]), name='biases')
print(weights)
print(biases)

<tf.Variable 'Variable:0' shape=(100, 100) dtype=float32, numpy=
array([[ 1.5813867 , -0.6882985 , -0.7991357 , ...,  0.36918125,
         0.5617364 ,  0.05332343],
       [-0.2282248 , -1.1420467 , -3.4893048 , ...,  1.4463179 ,
         1.4413028 ,  1.1665883 ],
       [-2.3497887 ,  0.37375766,  0.01055123, ...,  2.200192  ,
         0.22346704, -1.2937336 ],
       ...,
       [ 2.503373  , -0.49504036, -3.0083208 , ..., -0.13171336,
         0.8543077 ,  2.580464  ],
       [ 4.665003  , -0.6223454 ,  0.2639708 , ...,  2.9704897 ,
        -0.828054  ,  1.0430993 ],
       [ 1.6345584 , -5.3227587 ,  0.7710134 , ..., -1.8146482 ,
        -1.1949704 , -0.8628086 ]], dtype=float32)>
<tf.Variable 'biases:0' shape=(100,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.,