In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

2.3.0
2.4.0


In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

# 正則化器
# kernel_regularizer 應用於權重
# bias_regularizer 應用於偏差單元
# activity_regularizer 應用於層激活

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.categorical_crossentropy,metrics=[tf.keras.metrics.categorical_accuracy])

In [3]:
import numpy as np
train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100, validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 0s 21ms/step - loss: 11.9134 - categorical_accuracy: 0.1030 - val_loss: 12.2348 - val_categorical_accuracy: 0.1000
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 12.4632 - categorical_accuracy: 0.1050 - val_loss: 13.0779 - val_categorical_accuracy: 0.0750
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 13.5959 - categorical_accuracy: 0.1010 - val_loss: 14.5777 - val_categorical_accuracy: 0.0800
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 15.4239 - categorical_accuracy: 0.1000 - val_loss: 16.8219 - val_categorical_accuracy: 0.0850
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 18.1237 - categorical_accuracy: 0.1000 - val_loss: 20.0801 - val_categorical_accuracy: 0.0800
Epoch 6/10
10/10 [==============================] - 0s 3ms/step - loss: 21.8591 - categorical_accuracy: 0.1020 - val_loss: 24.1848 - val_categorical_accuracy: 0.1000
Epo

In [4]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()

val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30, validation_data=val_dataset, validation_steps=3)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

30/30 [==============================] - 0s 10ms/step - loss: 63.3665 - categorical_accuracy: 0.1135 - val_loss: 81.6824 - val_categorical_accuracy: 0.0833
Epoch 2/10
30/30 [==============================] - 0s 2ms/step - loss: 98.5012 - categorical_accuracy: 0.1058 - val_loss: 119.6443 - val_categorical_accuracy: 0.0729
Epoch 3/10
30/30 [==============================] - 0s 2ms/step - loss: 136.7587 - categorical_accuracy: 0.1036 - val_loss: 158.5972 - val_categorical_accuracy: 0.1562
Epoch 

In [6]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)

30/30 [==============================] - 0s 1ms/step - loss: 233.7585 - categorical_accuracy: 0.1021


[233.75845336914062, 0.10208333283662796]

In [7]:
result = model.predict(test_x, batch_size=32)
print(result)

[[0.18728863 0.4559118  0.14430206 ... 0.06930453 0.         0.0266932 ]
 [0.24732514 0.2843916  0.25368527 ... 0.09424144 0.         0.05502426]
 [0.10989207 0.3303275  0.24404441 ... 0.11652344 0.         0.07582325]
 ...
 [0.1363106  0.33968613 0.23164581 ... 0.15476212 0.         0.04521462]
 [0.17738603 0.2545905  0.24966627 ... 0.14506131 0.         0.0648121 ]
 [0.28359172 0.2187151  0.21743731 ... 0.11649952 0.         0.06247961]]
