In [1]:
# 佔位符
import tensorflow as tf
import numpy as np
t1 = np.array([1, 2, 3])
t2 = tf.convert_to_tensor(t1)
print(t2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [2]:
t3 = tf.zeros([2, 3], tf.int32)
print(t3)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [3]:
t4 = tf.ones([2, 3], tf.bool)
print(t4)

tf.Tensor(
[[ True  True  True]
 [ True  True  True]], shape=(2, 3), dtype=bool)


In [4]:
t5 = tf.linspace(2.0, 5, 5)
print(t5)

tf.Tensor([2.   2.75 3.5  4.25 5.  ], shape=(5,), dtype=float32)


In [5]:
t6 = tf.ones(7)
t7 = tf.Variable(t6, name='Q_Q')
print(t7)

<tf.Variable 'Q_Q:0' shape=(7,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)>


In [6]:
print(t7.trainable)

True


In [7]:
t8 = tf.zeros([6, 6], tf.int32)
print(t8)

tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]], shape=(6, 6), dtype=int32)


In [8]:
t9 = tf.random.normal([2, 3], mean=2, stddev=4, seed=12)
print(t9)

tf.Tensor(
[[ 0.25347447  5.37991     1.9527606 ]
 [-1.5376031   1.2588985   2.8478067 ]], shape=(2, 3), dtype=float32)


In [9]:
t10 = tf.random.truncated_normal([1, 5], stddev=2, seed=12)
print(t10)

tf.Tensor([[-0.87326276  1.689955   -0.02361972 -1.7688016  -3.87749   ]], shape=(1, 5), dtype=float32)


In [10]:
print(tf.random.uniform([2, 3], maxval=4, seed=12))

tf.Tensor(
[[2.54461   3.6963658 2.7051091]
 [2.0085006 3.8445983 3.5426888]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.range(10))
print(tf.range(2, 10))
print(tf.range(2, 10, 2))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)


In [15]:
tf.Variable(tf.ones(6), name='test').trainable

True

In [29]:
t11 = tf.zeros([2, 3], tf.int64)
t12 = tf.zeros_like(t11)
print(t12)
t13 = tf.fill([6, 6], 0)
print(t13)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]], shape=(6, 6), dtype=int32)
