In [1]:
import tensorflow as tf

In [9]:
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.square(2) + tf.square(3))

tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [12]:
# 矩陣相乘
tf.matmul([[1]], [[2, 3]])

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>