In [2]:
try:
    %tensorflow_version 2.x
except Exception:
    pass

In [3]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [4]:
t1 = tf.constant(4)
print(t1)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
t2 = tf.constant([1, 3])
print(t2)

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [6]:
import numpy as np
t3 = np.array([1, 2, 3])
t4 = tf.convert_to_tensor(t3)
print(t4)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
t5 = tf.zeros([2, 3], tf.int32)
print(t5)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [8]:
t6 = tf.ones([2, 3], tf.int32)
print(t6)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [9]:
t7 = tf.linspace(2.0, 5.0, 5)
print(t7)

tf.Tensor([2.   2.75 3.5  4.25 5.  ], shape=(5,), dtype=float32)


In [10]:
t8 = tf.range(2.0, 5.0, 0.75)
print(t8)

tf.Tensor([2.   2.75 3.5  4.25], shape=(4,), dtype=float32)


In [6]:
t9 = tf.Variable(t6, name='XyZ')
print(t9)

<tf.Variable 'XyZ:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>


In [11]:
t10 = tf.constant("123 abc")
print(t10)

tf.Tensor(b'123 abc', shape=(), dtype=string)
